In [2]:
from PIL import Image 
import pandas as pd
from pandas import DataFrame
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.hstack([[-1],a[:-1]])

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [11]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
b = a[:,1]
b

array([1, 5, 9])

In [13]:
b[2] = 10000

In [14]:
a

array([[    0,     1,     2,     3],
       [    4,     5,     6,     7],
       [    8, 10000,    10,    11]])

In [21]:
np.dtype('uint32').itemsize

4

In [24]:
a = np.array([1,2,3,1,5,6,1,7,8])
np.bincount(a, minlength=15)

array([0, 3, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [28]:
ddd = np.load('../../lbp_skimage.npy')
ddd.shape

(180, 151, 114)

In [4]:
img = Image.open("../../data/1.tiff")

In [5]:
img.filename

'../../data/1.tiff'

In [9]:
radii_list = [1,2,3]
npoints_list = [10,20,30]
channel_list = [0,1,2]
patchsize = 100
imgname = "img1"

In [10]:
jobs = DataFrame(index=pd.MultiIndex.from_product([channel_list, radii_list], names=['channel', 'radius']), columns=['channel','radius','img_name','label','npoints','patchsize'])
jobs['img_name'] = imgname
for c in channel_list: 
    jobs.loc[c,'channel'] = c
    jobs.loc[c,'radius'] = radii_list
    jobs.loc[c,'npoints'] = npoints_list
jobs['label'] = jobs.apply(lambda row: f"{imgname}_c{row.name[0]}_r{row.name[1]}_p{row['npoints']}", axis='columns')
jobs['patchsize'] = patchsize
jobs

channel radius img_name           label npoints  patchsize
channel radius                                                           
0       1            0      1     img1  img1_c0_r1_p10      10        100
        2            0      2     img1  img1_c0_r2_p20      20        100
        3            0      3     img1  img1_c0_r3_p30      30        100
1       1            1      1     img1  img1_c1_r1_p10      10        100
        2            1      2     img1  img1_c1_r2_p20      20        100
        3            1      3     img1  img1_c1_r3_p30      30        100
2       1            2      1     img1  img1_c2_r1_p10      10        100
        2            2      2     img1  img1_c2_r2_p20      20        100
        3            2      3     img1  img1_c2_r3_p30      30        100

In [15]:
list(jobs.loc[0].iterrows())

[(1,
  channel                   0
  radius                    1
  img_name               img1
  label        img1_c0_r1_p10
  npoints                  10
  patchsize               100
  Name: 1, dtype: object),
 (2,
  channel                   0
  radius                    2
  img_name               img1
  label        img1_c0_r2_p20
  npoints                  20
  patchsize               100
  Name: 2, dtype: object),
 (3,
  channel                   0
  radius                    3
  img_name               img1
  label        img1_c0_r3_p30
  npoints                  30
  patchsize               100
  Name: 3, dtype: object)]

In [9]:
jobs.loc[0,'npoints'] = [10,20,30]

In [6]:
jobs = DataFrame(index=pd.MultiIndex.from_product([channel_list, radii_list], names=['channel', 'radius']))
for c in channel_list: 
    jobs.loc[c,'npoints'] = npoints_list
jobs

NameError: name 'DataFrame' is not defined

In [11]:
jobs.loc[0,2].index

Index(['npoints'], dtype='object')

In [1]:
import fastlbp
import numpy as np
from PIL import Image 

In [2]:
img = Image.open("../../data/1.tiff")
img_data = np.asarray(img)
img_data.shape

(512, 512)

In [3]:
img_data = img_data[:,:,None]
img_data.shape

(512, 512, 1)

In [4]:
radii_list = [1,2,3,4,5]
npoints_list = [8,12,16,24,35]
patchsize = 64

fastlbp.run_skimage(img_data, radii_list, npoints_list, patchsize, ncpus=1, max_ram=100)

INFO:fastlbp:run_skimage: jobs:
INFO:fastlbp:               channel radius img_name          label npoints  patchsize  \
channel radius                                                             
0       1            0      1      img   img_c0_r1_p8       8         64   
        2            0      2      img  img_c0_r2_p12      12         64   
        3            0      3      img  img_c0_r3_p16      16         64   
        4            0      4      img  img_c0_r4_p24      24         64   
        5            0      5      img  img_c0_r5_p35      35         64   

               img_data  
channel radius           
0       1           NaN  
        2           NaN  
        3           NaN  
        4           NaN  
        5           NaN  
INFO:fastlbp:run_skimage: creating shared memory
INFO:fastlbp:run_skimage: start computation


TypeError: 'module' object is not callable

In [5]:
obs

NameError: name 'obs' is not defined